update scope and objectives
Rutu136/Comp4050-Project-Management pull request #4
Opened 2023-09-28 20:50 UTC by bre9425

2023-09-28 22:20 UTC, Rutu136 requested changes

2023-09-28 22:20 UTC, Rutu136 commented on Project_Charter.markdown
> +The ability to integrate with any other third party applications not previously specified will not be provided.
I think you're missing "and" here at the end, before will not be provided?

2023-09-28 22:20 UTC, Rutu136 commented on Project_Charter.markdown
>  ## Scope
Do we want to put scope for MVP and full project separate or together?
and
I was just wondering if we could just separate our points into two sections: 
inclusive boundaries: 
exclusive boundaries:
- Video calls are not allowed.
- Will not supply the servers, hardware or OS
- Integration with other third party app is not supported.

2023-09-28 22:20 UTC, Rutu136 commented on Project_Charter.markdown
>  ## Objectives
Looks good!

2023-09-29 21:07 UTC, Rutu136 approved these changes

2023-09-29 21:09 UTC, dkanghan approved these changes

2023-09-29 21:10 UTC, merged